task:
  name: Build Matplotlib on FreeBSD
  freebsd_instance:
    image_family: freebsd-14-0
  env:
    PYTHON_VERSION: 3.10
  install_script:
    - sudo pkg update
    - sudo pkg install -y python${PYTHON_VERSION} gcc wget
    - sudo pkg install -y py${PYTHON_VERSION}-venv  # 安装 venv 模块
  script:
    - python${PYTHON_VERSION} -m venv venv  # 创建虚拟环境
    - source venv/bin/activate  # 激活虚拟环境
    - pip install --upgrade pip setuptools wheel  # 安装 pip、setuptools 和 wheel
    - wget https://github.com/matplotlib/matplotlib/archive/refs/tags/v3.9.1.tar.gz
    - tar -xzf v3.9.1.tar.gz
    - cd matplotlib-3.9.1
    - pip install -r requirements/build.txt
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - matplotlib-3.9.1/dist/*.whl

