task:
  name: Build Matplotlib on FreeBSD
  freebsd_instance:
    image_family: freebsd-14-0
  env:
    PYTHON_VERSION: 3.10
  install_script:
    - sudo pkg update
    - sudo pkg install -y python${PYTHON_VERSION} gcc wget
    - sudo pkg install -y py${PYTHON_VERSION}-venv  # 安装 venv 模块
  script:
    - python${PYTHON_VERSION} -m venv venv  # 创建虚拟环境
    - source venv/bin/activate  # 激活虚拟环境
    - pip install --upgrade pip setuptools wheel  # 安装 pip、setuptools 和 wheel
    - pip install --no-binary matplotlib matplotlib  # 下载并编译 matplotlib 及其所有依赖项
  artifacts:
    paths:
      - venv/lib/python${PYTHON_VERSION}/site-packages/*.whl

